const wordPairs = [];
const uniquePairs = [
  // Рівень A1
  { en: "apple", ua: "яблуко", level: "A1" },
  { en: "house", ua: "будинок", level: "A1" },
  { en: "car", ua: "автомобіль", level: "A1" },
  { en: "water", ua: "вода", level: "A1" },
  { en: "frog", ua: "жаба", level: "A1" },
  { en: "bucket", ua: "відро", level: "A1" },
  { en: "bridge", ua: "міст", level: "A1" },
  { en: "countryside", ua: "сільська місцевість", level: "A1" },
  { en: "island", ua: "острів", level: "A1" },
  { en: "population", ua: "населення", level: "A1" },
  { en: "adventure", ua: "пригоди", level: "A1" },
  { en: "description", ua: "опис", level: "A1" },
  { en: "schedule", ua: "розклад", level: "A1" },
  { en: "celebration", ua: "святкування", level: "A1" },

  { en: "beautiful", ua: "гарний", level: "A1" },
  { en: "important", ua: "важливий", level: "A1" },
  { en: "interesting", ua: "цікавий", level: "A1" },
  { en: "modern", ua: "сучасний", level: "A1" },
  { en: "traditional", ua: "традиційний", level: "A1" },
  { en: "natural", ua: "природний", level: "A1" },

  { en: "improve", ua: "покращувати", level: "A1" },
  { en: "describe", ua: "описувати", level: "A1" },
  { en: "continue", ua: "продовжувати", level: "A1" },
  { en: "build", ua: "будувати", level: "A1" },
  { en: "celebrate", ua: "святкувати", level: "A1" },
  { en: "explain", ua: "пояснювати", level: "A1" },
  { en: "prefer", ua: "надавати перевагу", level: "A1" },
  { en: "recommend", ua: "рекомендувати", level: "A1" },
  { en: "repair", ua: "ремонтувати", level: "A1" },

  { en: "language", ua: "мова", level: "A1" },
  { en: "city", ua: "місто", level: "A1" },
  { en: "river", ua: "річка", level: "A1" },
  { en: "advice", ua: "порада", level: "A1" },
  { en: "village", ua: "село", level: "A1" },
  { en: "mountain", ua: "гора", level: "A1" },
  { en: "holiday", ua: "відпустка", level: "A1" },

  { en: "brave", ua: "хоробрий", level: "A1" },
  { en: "clever", ua: "розумний", level: "A1" },
  { en: "polite", ua: "ввічливий", level: "A1" },
  { en: "dangerous", ua: "небезпечний", level: "A1" },
  { en: "quiet", ua: "тихий", level: "A1" },
  { en: "famous", ua: "відомий", level: "A1" },
  { en: "healthy", ua: "здоровий", level: "A1" },
  { en: "poor", ua: "бідний", level: "A1" },
  { en: "rich", ua: "багатий", level: "A1" },

  { en: "study", ua: "вчитися", level: "A1" },
  { en: "visit", ua: "відвідувати", level: "A1" },
  { en: "agree", ua: "погоджуватися", level: "A1" },
  { en: "choose", ua: "вибирати", level: "A1" },
  { en: "decide", ua: "вирішувати", level: "A1" },
  { en: "invite", ua: "запрошувати", level: "A1" },
  { en: "organize", ua: "організовувати", level: "A1" },
  { en: "travel", ua: "подорожувати", level: "A1" },

  { en: "suggest", ua: "пропонувати", level: "A1" },
  { en: "guess", ua: "здогадуватися", level: "A1" },
  { en: "borrow", ua: "позичати", level: "A1" },
  { en: "climb", ua: "лазити", level: "A1" },
  { en: "develop", ua: "розвивати", level: "A1" },
  { en: "discover", ua: "відкривати", level: "A1" },
  { en: "enjoy", ua: "насолоджуватися", level: "A1" },
  { en: "prepare", ua: "готуватися", level: "A1" },
  { en: "save", ua: "зберігати", level: "A1" },

  { en: "teacher", ua: "вчитель", level: "A1" },
  { en: "writer", ua: "письменник", level: "A1" },
  { en: "relationship", ua: "відносини", level: "A1" },

  { en: "intelligent", ua: "розумний", level: "A1" },
  { en: "strong", ua: "сильний", level: "A1" },
  { en: "kind", ua: "добрий", level: "A1" },
  { en: "lazy", ua: "лінивий", level: "A1" },
  { en: "helpful", ua: "корисний", level: "A1" },
  { en: "honest", ua: "чесний", level: "A1" },
  { en: "organized", ua: "організований", level: "A1" },
  { en: "serious", ua: "серйозний", level: "A1" },
  { en: "busy", ua: "зайнятий", level: "A1" },

  // Рівень A1
  { en: "comfortable", ua: "зручний", level: "A1" },
  { en: "creative", ua: "креативний", level: "A1" },
  { en: "difficult", ua: "важкий", level: "A1" },
  { en: "early", ua: "ранній", level: "A1" },
  { en: "expensive", ua: "дорогий", level: "A1" },
  { en: "perfect", ua: "ідеальний", level: "A1" },
  { en: "strange", ua: "дивний", level: "A1" },
  { en: "simple", ua: "простий", level: "A1" },
  { en: "useful", ua: "корисний", level: "A1" },
  { en: "young", ua: "молодий", level: "A1" },

  { en: "author", ua: "автор", level: "A1" },
  { en: "basket", ua: "кошик", level: "A1" },
  { en: "concert", ua: "концерт", level: "A1" },
  { en: "customer", ua: "клієнт", level: "A1" },
  { en: "festival", ua: "фестиваль", level: "A1" },
  { en: "nature", ua: "природа", level: "A1" },

  { en: "arrive", ua: "приїжджати", level: "A1" },
  { en: "belong", ua: "належати", level: "A1" },
  { en: "laugh", ua: "сміятися", level: "A1" },
  { en: "paint", ua: "малювати", level: "A1" },
  { en: "reply", ua: "відповідати", level: "A1" },
  { en: "return", ua: "повертатися", level: "A1" },
  { en: "share", ua: "ділитися", level: "A1" },
  { en: "spend", ua: "витрачати", level: "A1" },

  // Рівень A1
  { en: "introduce", ua: "представляти", level: "A1" },
  { en: "accept", ua: "приймати", level: "A1" },
  { en: "decide", ua: "вирішувати", level: "A1" },
  { en: "wake", ua: "прокидатися", level: "A1" },
  { en: "count", ua: "рахувати", level: "A1" },
  { en: "clean", ua: "чистити", level: "A1" },
  { en: "happen", ua: "траплятися", level: "A1" },
  { en: "include", ua: "включати", level: "A1" },
  { en: "allow", ua: "дозволяти", level: "A1" },
  { en: "wonder", ua: "цікавитися", level: "A1" },

  { en: "chance", ua: "шанс", level: "A1" },
  { en: "choice", ua: "вибір", level: "A1" },
  { en: "goal", ua: "мета", level: "A1" },
  { en: "idea", ua: "ідея", level: "A1" },
  { en: "opinion", ua: "думка", level: "A1" },
  { en: "plan", ua: "план", level: "A1" },
  { en: "project", ua: "проєкт", level: "A1" },
  { en: "result", ua: "результат", level: "A1" },
  { en: "solution", ua: "рішення", level: "A1" },
  { en: "success", ua: "успіх", level: "A1" },

  { en: "different", ua: "різний", level: "A1" },
  { en: "special", ua: "особливий", level: "A1" },
  { en: "important", ua: "важливий", level: "A1" },
  { en: "difficult", ua: "важкий", level: "A1" },
  { en: "possible", ua: "можливий", level: "A1" },
  { en: "correct", ua: "правильний", level: "A1" },
  { en: "ready", ua: "готовий", level: "A1" },
  { en: "true", ua: "правдивий", level: "A1" },
  { en: "whole", ua: "цілий", level: "A1" },

  // Рівень A1
  { en: "clear", ua: "чистий", level: "A1" },
  { en: "dirty", ua: "брудний", level: "A1" },
  { en: "problem", ua: "проблема", level: "A1" },
  { en: "music", ua: "музика", level: "A1" },
  { en: "party", ua: "вечірка", level: "A1" },
  { en: "event", ua: "подія", level: "A1" },
  { en: "travel", ua: "подорож", level: "A1" },
  { en: "object", ua: "об'єкт", level: "A1" },

  { en: "move", ua: "рухатися", level: "A1" },
  { en: "grow", ua: "рости", level: "A1" },
  { en: "change", ua: "змінювати", level: "A1" },
  { en: "meet", ua: "зустрічати", level: "A1" },

  { en: "reason", ua: "причина", level: "A1" },
  { en: "truth", ua: "правда", level: "A1" },
  { en: "lie", ua: "брехня", level: "A1" },
  { en: "wish", ua: "бажання", level: "A1" },
  { en: "dream", ua: "мрія", level: "A1" },
  { en: "hope", ua: "надія", level: "A1" },
  { en: "future", ua: "майбутнє", level: "A1" },
  { en: "past", ua: "минуле", level: "A1" },
  { en: "present", ua: "теперішнє", level: "A1" },

  // Рівень A1
  { en: "activity", ua: "діяльність", level: "A1" },
  { en: "adventure", ua: "пригоди", level: "A1" },
  { en: "background", ua: "фон", level: "A1" },
  { en: "celebration", ua: "святкування", level: "A1" },
  { en: "competition", ua: "змагання", level: "A1" },
  { en: "conversation", ua: "розмова", level: "A1" },
  { en: "decision", ua: "рішення", level: "A1" },
  { en: "destination", ua: "пункт призначення", level: "A1" },
  { en: "equipment", ua: "обладнання", level: "A1" },
  { en: "experience", ua: "досвід", level: "A1" },

  { en: "favorite", ua: "улюблений", level: "A1" },
  { en: "freedom", ua: "свобода", level: "A1" },
  { en: "information", ua: "інформація", level: "A1" },
  { en: "knowledge", ua: "знання", level: "A1" },
  { en: "movement", ua: "рух", level: "A1" },
  { en: "opportunity", ua: "можливість", level: "A1" },
  { en: "possibility", ua: "можливість", level: "A1" },
  { en: "recommendation", ua: "рекомендація", level: "A1" },
  { en: "situation", ua: "ситуація", level: "A1" },
  { en: "universe", ua: "всесвіт", level: "A1" },

  { en: "create", ua: "створювати", level: "A1" },
  { en: "express", ua: "виражати", level: "A1" },
  { en: "imagine", ua: "уявляти", level: "A1" },
  { en: "prepare", ua: "готувати", level: "A1" },
  { en: "protect", ua: "захищати", level: "A1" },
  { en: "realize", ua: "усвідомлювати", level: "A1" },
  { en: "recognize", ua: "розпізнавати", level: "A1" },
  { en: "celebrate", ua: "святкувати", level: "A1" },
  { en: "introduce", ua: "представляти", level: "A1" },
  { en: "understand", ua: "розуміти", level: "A1" },

  // Рівень A1
  { en: "admit", ua: "визнавати", level: "A1" },
  { en: "advise", ua: "радити", level: "A1" },
  { en: "allow", ua: "дозволяти", level: "A1" },
  { en: "arrange", ua: "організовувати", level: "A1" },
  { en: "avoid", ua: "уникати", level: "A1" },
  { en: "breathe", ua: "дихати", level: "A1" },
  { en: "collect", ua: "збирати", level: "A1" },
  { en: "deliver", ua: "доставляти", level: "A1" },
  { en: "educate", ua: "навчати", level: "A1" },
  { en: "explore", ua: "досліджувати", level: "A1" },

  { en: "faith", ua: "віра", level: "A1" },
  { en: "health", ua: "здоров'я", level: "A1" },
  { en: "income", ua: "дохід", level: "A1" },
  { en: "justice", ua: "справедливість", level: "A1" },
  { en: "memory", ua: "пам'ять", level: "A1" },
  { en: "network", ua: "мережа", level: "A1" },
  { en: "progress", ua: "прогрес", level: "A1" },
  { en: "respect", ua: "повага", level: "A1" },
  { en: "safety", ua: "безпека", level: "A1" },
  { en: "strength", ua: "сила", level: "A1" },

  { en: "gentle", ua: "ніжний", level: "A1" },
  { en: "honest", ua: "чесний", level: "A1" },
  { en: "lucky", ua: "щасливий", level: "A1" },
  { en: "mature", ua: "зрілий", level: "A1" },
  { en: "patient", ua: "терплячий", level: "A1" },
  { en: "reliable", ua: "надійний", level: "A1" },
  { en: "sensible", ua: "розсудливий", level: "A1" },
  { en: "trustworthy", ua: "той, кому можна довіряти", level: "A1" },
  { en: "wise", ua: "мудрий", level: "A1" },
  { en: "youthful", ua: "молодий", level: "A1" },

  // Рівень A1
  { en: "calm", ua: "спокійний", level: "A1" },
  { en: "brilliant", ua: "блискучий", level: "A1" },
  { en: "careful", ua: "обережний", level: "A1" },
  { en: "confident", ua: "впевнений", level: "A1" },
  { en: "curious", ua: "цікавий", level: "A1" },
  { en: "generous", ua: "щедрий", level: "A1" },
  { en: "grateful", ua: "вдячний", level: "A1" },
  { en: "hardworking", ua: "працьовитий", level: "A1" },
  { en: "helpful", ua: "корисний", level: "A1" },
  { en: "independent", ua: "незалежний", level: "A1" },

  { en: "journey", ua: "подорож", level: "A1" },
  { en: "knowledge", ua: "знання", level: "A1" },
  { en: "landscape", ua: "ландшафт", level: "A1" },
  { en: "legend", ua: "легенда", level: "A1" },
  { en: "literature", ua: "література", level: "A1" },
  { en: "painting", ua: "картина", level: "A1" },
  { en: "performance", ua: "вистава", level: "A1" },
  { en: "population", ua: "населення", level: "A1" },

  { en: "appear", ua: "з'являтися", level: "A1" },
  { en: "arrive", ua: "прибувати", level: "A1" },
  { en: "build", ua: "будувати", level: "A1" },
  { en: "discover", ua: "відкривати", level: "A1" },
  { en: "explore", ua: "досліджувати", level: "A1" },
  { en: "improve", ua: "покращувати", level: "A1" },
  { en: "organize", ua: "організовувати", level: "A1" },
  { en: "perform", ua: "виконувати", level: "A1" },
  { en: "recommend", ua: "рекомендувати", level: "A1" },
  { en: "repair", ua: "ремонтувати", level: "A1" },

  // Рівень A1
  { en: "solution", ua: "рішення", level: "A1" },
  { en: "task", ua: "завдання", level: "A1" },
  { en: "team", ua: "команда", level: "A1" },
  { en: "topic", ua: "тема", level: "A1" },
  { en: "tradition", ua: "традиція", level: "A1" },
  { en: "value", ua: "цінність", level: "A1" },
  { en: "view", ua: "вид", level: "A1" },
  { en: "visit", ua: "візит", level: "A1" },
  { en: "wonder", ua: "диво", level: "A1" },

  // Рівень A1
  { en: "adventure", ua: "пригоди", level: "A1" },
  { en: "advice", ua: "порада", level: "A1" },
  { en: "agreement", ua: "угода", level: "A1" },
  { en: "ambition", ua: "амбіція", level: "A1" },
  { en: "appointment", ua: "зустріч", level: "A1" },
  { en: "assistant", ua: "помічник", level: "A1" },
  { en: "attitude", ua: "ставлення", level: "A1" },
  { en: "attraction", ua: "привабливість", level: "A1" },
  { en: "attention", ua: "увага", level: "A1" },
  { en: "average", ua: "середнє", level: "A1" },

  { en: "celebration", ua: "святкування", level: "A1" },
  { en: "connection", ua: "зв'язок", level: "A1" },
  { en: "destination", ua: "пункт призначення", level: "A1" },
  { en: "difficulty", ua: "складність", level: "A1" },
  { en: "direction", ua: "напрямок", level: "A1" },
  { en: "discussion", ua: "обговорення", level: "A1" },
  { en: "education", ua: "освіта", level: "A1" },
  { en: "environment", ua: "навколишнє середовище", level: "A1" },
  { en: "explanation", ua: "пояснення", level: "A1" },
  { en: "foundation", ua: "основа", level: "A1" },

  { en: "comfortable", ua: "зручний", level: "A1" },
  { en: "delicious", ua: "смачний", level: "A1" },
  { en: "distant", ua: "віддалений", level: "A1" },
  { en: "economical", ua: "економічний", level: "A1" },
  { en: "effective", ua: "ефективний", level: "A1" },
  { en: "fascinating", ua: "захоплюючий", level: "A1" },
  { en: "impressive", ua: "вражаючий", level: "A1" },
  { en: "mysterious", ua: "загадковий", level: "A1" },
  { en: "professional", ua: "професійний", level: "A1" },
  { en: "successful", ua: "успішний", level: "A1" },

  // Рівень A1
  { en: "achievement", ua: "досягнення", level: "A1" },
  { en: "agreement", ua: "угода", level: "A1" },
  { en: "ambition", ua: "амбіція", level: "A1" },
  { en: "assistance", ua: "допомога", level: "A1" },
  { en: "choice", ua: "вибір", level: "A1" },
  { en: "contribution", ua: "внесок", level: "A1" },
  { en: "enthusiasm", ua: "ентузіазм", level: "A1" },
  { en: "explanation", ua: "пояснення", level: "A1" },
  { en: "improvement", ua: "покращення", level: "A1" },
  { en: "performance", ua: "вистава", level: "A1" },

  { en: "brilliant", ua: "блискучий", level: "A1" },
  { en: "competitive", ua: "конкурентний", level: "A1" },
  { en: "confident", ua: "впевнений", level: "A1" },
  { en: "determined", ua: "рішучий", level: "A1" },
  { en: "effective", ua: "ефективний", level: "A1" },
  { en: "fortunate", ua: "щасливий", level: "A1" },
  { en: "generous", ua: "щедрий", level: "A1" },
  { en: "knowledgeable", ua: "знаючий", level: "A1" },
  { en: "productive", ua: "продуктивний", level: "A1" },
  { en: "supportive", ua: "підтримуючий", level: "A1" },

  { en: "analyze", ua: "аналізувати", level: "A1" },
  { en: "attempt", ua: "намагатися", level: "A1" },
  { en: "communicate", ua: "спілкуватися", level: "A1" },
  { en: "contribute", ua: "вносити вклад", level: "A1" },
  { en: "demonstrate", ua: "демонструвати", level: "A1" },
  { en: "evaluate", ua: "оцінювати", level: "A1" },
  { en: "participate", ua: "брати участь", level: "A1" },
  { en: "progress", ua: "просуватися", level: "A1" },
  { en: "respond", ua: "відповідати", level: "A1" },
  { en: "succeed", ua: "досягати успіху", level: "A1" },

  // Рівень A1
  { en: "achieve", ua: "досягати", level: "A1" },
  { en: "argue", ua: "сперечатися", level: "A1" },
  { en: "calculate", ua: "обчислювати", level: "A1" },
  { en: "compare", ua: "порівнювати", level: "A1" },
  { en: "depend", ua: "залежати", level: "A1" },
  { en: "discuss", ua: "обговорювати", level: "A1" },
  { en: "encourage", ua: "заохочувати", level: "A1" },
  { en: "identify", ua: "визначати", level: "A1" },
  { en: "reflect", ua: "відображати", level: "A1" },

  { en: "responsibility", ua: "відповідальність", level: "A1" },
  { en: "effort", ua: "зусилля", level: "A1" },
  { en: "expectation", ua: "очікування", level: "A1" },
  { en: "goal", ua: "мета", level: "A1" },
  { en: "invention", ua: "винахід", level: "A1" },
  { en: "opinion", ua: "думка", level: "A1" },
  { en: "progress", ua: "прогрес", level: "A1" },
  { en: "resource", ua: "ресурс", level: "A1" },
  { en: "solution", ua: "рішення", level: "A1" },

  { en: "brave", ua: "хоробрий", level: "A1" },
  { en: "calm", ua: "спокійний", level: "A1" },
  { en: "dynamic", ua: "динамічний", level: "A1" },
  { en: "efficient", ua: "ефективний", level: "A1" },
  { en: "innovative", ua: "інноваційний", level: "A1" },
  { en: "logical", ua: "логічний", level: "A1" },
  { en: "optimistic", ua: "оптимістичний", level: "A1" },
  { en: "practical", ua: "практичний", level: "A1" },
  { en: "realistic", ua: "реалістичний", level: "A1" },
  { en: "responsible", ua: "відповідальний", level: "A1" },

  // Рівень A1
  { en: "scientist", ua: "вчений", level: "A1" },
  { en: "adventure", ua: "пригода", level: "A1" },
  { en: "challenge", ua: "виклик", level: "A1" },
  { en: "decision", ua: "рішення", level: "A1" },
  { en: "effect", ua: "ефект", level: "A1" },
  { en: "example", ua: "приклад", level: "A1" },
  { en: "focus", ua: "увага", level: "A1" },
  { en: "height", ua: "висота", level: "A1" },
  { en: "option", ua: "варіант", level: "A1" },
  { en: "reaction", ua: "реакція", level: "A1" },

  { en: "admit", ua: "визнавати", level: "A1" },
  { en: "allow", ua: "дозволяти", level: "A1" },
  { en: "analyze", ua: "аналізувати", level: "A1" },
  { en: "conclude", ua: "робити висновок", level: "A1" },
  { en: "depend", ua: "залежати", level: "A1" },
  { en: "express", ua: "виражати", level: "A1" },
  { en: "manage", ua: "керувати", level: "A1" },
  { en: "organize", ua: "організовувати", level: "A1" },
  { en: "realize", ua: "усвідомлювати", level: "A1" },
  { en: "reflect", ua: "відображати", level: "A1" },

  { en: "complicated", ua: "складний", level: "A1" },
  { en: "creative", ua: "творчий", level: "A1" },
  { en: "detailed", ua: "детальний", level: "A1" },
  { en: "enthusiastic", ua: "ентузіастичний", level: "A1" },
  { en: "flexible", ua: "гнучкий", level: "A1" },
  { en: "helpful", ua: "корисний", level: "A1" },
  { en: "logical", ua: "логічний", level: "A1" },
  { en: "motivated", ua: "мотивований", level: "A1" },
  { en: "positive", ua: "позитивний", level: "A1" },
  { en: "realistic", ua: "реалістичний", level: "A1" },
  // Рівень A1
  { en: "accurate", ua: "точний", level: "A1" },
  { en: "bold", ua: "сміливий", level: "A1" },
  { en: "confident", ua: "впевнений", level: "A1" },
  { en: "independent", ua: "незалежний", level: "A1" },
  { en: "remarkable", ua: "видатний", level: "A1" },
  { en: "significant", ua: "значний", level: "A1" },
  { en: "unique", ua: "унікальний", level: "A1" },
  { en: "wealthy", ua: "заможний", level: "A1" },
  { en: "welcome", ua: "ласкавий", level: "A1" },
  { en: "wonderful", ua: "чудовий", level: "A1" },

  // Рівень A1
  { en: "bright", ua: "яскравий", level: "A1" },
  { en: "dark", ua: "темний", level: "A1" },
  { en: "deep", ua: "глибокий", level: "A1" },
  { en: "narrow", ua: "вузький", level: "A1" },
  { en: "wide", ua: "широкий", level: "A1" },
  { en: "thin", ua: "тонкий", level: "A1" },
  { en: "thick", ua: "товстий", level: "A1" },
  { en: "clean", ua: "чистий", level: "A1" },
  { en: "dirty", ua: "брудний", level: "A1" },
  { en: "soft", ua: "м'який", level: "A1" },

  { en: "sharp", ua: "гострий", level: "A1" },
  { en: "smooth", ua: "гладкий", level: "A1" },
  { en: "rough", ua: "шорсткий", level: "A1" },
  { en: "heavy", ua: "важкий", level: "A1" },
  { en: "light", ua: "легкий", level: "A1" },
  { en: "sticky", ua: "липкий", level: "A1" },
  { en: "wet", ua: "мокрий", level: "A1" },
  { en: "dry", ua: "сухий", level: "A1" },
  { en: "loud", ua: "гучний", level: "A1" },
  { en: "quiet", ua: "тихий", level: "A1" },

  { en: "support", ua: "підтримка", level: "A1" },
  { en: "strength", ua: "сила", level: "A1" },
  { en: "weakness", ua: "слабкість", level: "A1" },
  { en: "confidence", ua: "впевненість", level: "A1" },
  { en: "skill", ua: "навичка", level: "A1" },
  { en: "opportunity", ua: "можливість", level: "A1" },
  { en: "responsibility", ua: "відповідальність", level: "A1" },
  { en: "chance", ua: "шанс", level: "A1" },
  { en: "success", ua: "успіх", level: "A1" },
  { en: "failure", ua: "невдача", level: "A1" },
  // Рівень A1
  { en: "create", ua: "створювати", level: "A1" },
  { en: "design", ua: "розробляти", level: "A1" },
  { en: "discover", ua: "відкривати", level: "A1" },
  { en: "develop", ua: "розвивати", level: "A1" },
  { en: "improve", ua: "покращувати", level: "A1" },
  { en: "manage", ua: "керувати", level: "A1" },
  { en: "organize", ua: "організовувати", level: "A1" },
  { en: "solve", ua: "вирішувати", level: "A1" },
  { en: "support", ua: "підтримувати", level: "A1" },
  { en: "understand", ua: "розуміти", level: "A1" },
  // Рівень A1
  { en: "admire", ua: "захоплюватися", level: "A1" },
  { en: "adopt", ua: "приймати", level: "A1" },
  { en: "affect", ua: "впливати", level: "A1" },
  { en: "analyze", ua: "аналізувати", level: "A1" },
  { en: "argue", ua: "сперечатися", level: "A1" },
  { en: "arrange", ua: "організовувати", level: "A1" },
  { en: "assume", ua: "припускати", level: "A1" },
  { en: "belong", ua: "належати", level: "A1" },
  { en: "borrow", ua: "позичати", level: "A1" },
  { en: "calculate", ua: "обчислювати", level: "A1" },

  { en: "celebrate", ua: "святкувати", level: "A1" },
  { en: "compare", ua: "порівнювати", level: "A1" },
  { en: "complain", ua: "скаржитися", level: "A1" },
  { en: "confirm", ua: "підтверджувати", level: "A1" },
  { en: "connect", ua: "з'єднувати", level: "A1" },
  { en: "contact", ua: "контактувати", level: "A1" },
  { en: "contribute", ua: "вносити вклад", level: "A1" },
  { en: "control", ua: "контролювати", level: "A1" },
  { en: "create", ua: "створювати", level: "A1" },
  { en: "decide", ua: "вирішувати", level: "A1" },

  { en: "define", ua: "визначати", level: "A1" },
  { en: "deliver", ua: "доставляти", level: "A1" },
  { en: "depend", ua: "залежати", level: "A1" },
  { en: "describe", ua: "описувати", level: "A1" },
  { en: "design", ua: "розробляти", level: "A1" },
  { en: "develop", ua: "розвивати", level: "A1" },
  { en: "discover", ua: "відкривати", level: "A1" },
  { en: "discuss", ua: "обговорювати", level: "A1" },
  { en: "divide", ua: "ділити", level: "A1" },
  { en: "encourage", ua: "заохочувати", level: "A1" },
  // Рівень A1
  { en: "experience", ua: "досвідчувати", level: "A1" },
  { en: "imagine", ua: "уявляти", level: "A1" },
  { en: "increase", ua: "збільшувати", level: "A1" },
  { en: "influence", ua: "впливати", level: "A1" },
  { en: "investigate", ua: "розслідувати", level: "A1" },
  { en: "join", ua: "приєднуватися", level: "A1" },
  { en: "learn", ua: "вчитися", level: "A1" },
  { en: "move", ua: "рухатися", level: "A1" },
  { en: "notice", ua: "звертати увагу", level: "A1" },
  { en: "operate", ua: "керувати", level: "A1" },

  { en: "participate", ua: "брати участь", level: "A1" },
  { en: "practice", ua: "практикувати", level: "A1" },
  { en: "prepare", ua: "готуватися", level: "A1" },
  { en: "produce", ua: "виробляти", level: "A1" },
  { en: "recognize", ua: "розпізнавати", level: "A1" },
  { en: "repair", ua: "ремонтувати", level: "A1" },
  { en: "replace", ua: "замінювати", level: "A1" },
  { en: "respect", ua: "поважати", level: "A1" },
  { en: "search", ua: "шукати", level: "A1" },
  { en: "share", ua: "ділитися", level: "A1" },

  { en: "study", ua: "вивчати", level: "A1" },
  { en: "suggest", ua: "пропонувати", level: "A1" },
  { en: "support", ua: "підтримувати", level: "A1" },
  { en: "train", ua: "тренувати", level: "A1" },
  { en: "travel", ua: "подорожувати", level: "A1" },
  { en: "understand", ua: "розуміти", level: "A1" },
  { en: "use", ua: "використовувати", level: "A1" },
  { en: "value", ua: "цінувати", level: "A1" },
  { en: "volunteer", ua: "волонтерити", level: "A1" },
  // Рівень A1
  { en: "achieve", ua: "досягати", level: "A1" },
  { en: "adapt", ua: "адаптуватися", level: "A1" },
  { en: "advise", ua: "радити", level: "A1" },
  { en: "agree", ua: "погоджуватися", level: "A1" },
  { en: "assist", ua: "допомагати", level: "A1" },
  { en: "challenge", ua: "викликати", level: "A1" },
  { en: "clarify", ua: "уточнювати", level: "A1" },
  { en: "compare", ua: "порівнювати", level: "A1" },
  { en: "complain", ua: "скаржитися", level: "A1" },
  { en: "conclude", ua: "робити висновок", level: "A1" },

  // Рівень B1
  { en: "look after", ua: "піклуватися", level: "B1" },
  { en: "mistake", ua: "помилка", level: "B1" },
  { en: "friendship", ua: "дружба", level: "B1" },
  // Рівень B1
  { en: "analyze", ua: "аналізувати", level: "B1" },
  { en: "assist", ua: "допомагати", level: "B1" },
  { en: "criticize", ua: "критикувати", level: "B1" },
  { en: "debate", ua: "дискутувати", level: "B1" },
  { en: "defend", ua: "захищати", level: "B1" },
  { en: "evaluate", ua: "оцінювати", level: "B1" },
  { en: "interpret", ua: "інтерпретувати", level: "B1" },
  { en: "negotiate", ua: "переговорювати", level: "B1" },

  // Рівень B1
  { en: "acknowledge", ua: "визнавати", level: "B1" },
  { en: "anticipate", ua: "передбачати", level: "B1" },
  { en: "collaborate", ua: "співпрацювати", level: "B1" },
  { en: "differentiate", ua: "розрізняти", level: "B1" },
  { en: "elaborate", ua: "деталізувати", level: "B1" },
  { en: "facilitate", ua: "сприяти", level: "B1" },
  { en: "justify", ua: "виправдовувати", level: "B1" },
  { en: "optimize", ua: "оптимізувати", level: "B1" },
  { en: "synthesize", ua: "синтезувати", level: "B1" },
  // Рівень B1
  { en: "adjust", ua: "регулювати", level: "B1" },
  { en: "analyze", ua: "аналізувати", level: "B1" },
  { en: "assist", ua: "допомагати", level: "B1" },
  { en: "boost", ua: "підсилювати", level: "B1" },
  { en: "coordinate", ua: "координувати", level: "B1" },
  { en: "emphasize", ua: "наголошувати", level: "B1" },
  { en: "illustrate", ua: "ілюструвати", level: "B1" },
  { en: "influence", ua: "впливати", level: "B1" },
  { en: "inquire", ua: "запитувати", level: "B1" },
  { en: "investigate", ua: "розслідувати", level: "B1" },
  // Рівень B1
  { en: "manage", ua: "керувати", level: "B1" },
  { en: "operate", ua: "працювати", level: "B1" },
  { en: "recommend", ua: "рекомендувати", level: "B1" },
  { en: "represent", ua: "представляти", level: "B1" },
  { en: "resolve", ua: "вирішувати", level: "B1" },
  { en: "select", ua: "вибирати", level: "B1" },
  { en: "survey", ua: "опитувати", level: "B1" },
  { en: "testify", ua: "свідчити", level: "B1" },
  { en: "warn", ua: "попереджати", level: "B1" },
  { en: "apply", ua: "застосовувати", level: "B1" },

  // Рівень B1
  { en: "abolish", ua: "скасувати", level: "B1" },
  { en: "acquire", ua: "отримувати", level: "B1" },
  { en: "assemble", ua: "збирати", level: "B1" },
  { en: "comprehend", ua: "зрозуміти", level: "B1" },
  { en: "decrease", ua: "зменшувати", level: "B1" },
  { en: "enhance", ua: "покращувати", level: "B1" },
  { en: "establish", ua: "створювати", level: "B1" },
  { en: "expand", ua: "розширювати", level: "B1" },
  { en: "implement", ua: "впроваджувати", level: "B1" },
  { en: "prioritize", ua: "пріоритезувати", level: "B1" },
  // Рівень B1
  { en: "advertise", ua: "рекламувати", level: "B1" },
  { en: "categorize", ua: "класифікувати", level: "B1" },
  { en: "combine", ua: "поєднувати", level: "B1" },
  { en: "compete", ua: "змагатися", level: "B1" },
  { en: "evaluate", ua: "оцінювати", level: "B1" },
  { en: "monitor", ua: "контролювати", level: "B1" },
  { en: "publish", ua: "публікувати", level: "B1" },
  { en: "resolve", ua: "вирішувати", level: "B1" },
  { en: "revise", ua: "переглядати", level: "B1" },
  { en: "succeed", ua: "досягати успіху", level: "B1" },

  // Рівень B1
  { en: "allocate", ua: "розподіляти", level: "B1" },
  { en: "anticipate", ua: "очікувати", level: "B1" },
  { en: "collaborate", ua: "співпрацювати", level: "B1" },
  { en: "delegate", ua: "делегувати", level: "B1" },
  { en: "diversify", ua: "урізноманітнювати", level: "B1" },
  { en: "incorporate", ua: "включати", level: "B1" },
  { en: "negotiate", ua: "вести переговори", level: "B1" },
  { en: "sustain", ua: "підтримувати", level: "B1" },
  { en: "undertake", ua: "брати на себе", level: "B1" },
  { en: "validate", ua: "підтверджувати", level: "B1" },
  // Рівень B1
  { en: "accomplish", ua: "завершувати", level: "B1" },
  { en: "analyze", ua: "аналізувати", level: "B1" },
  { en: "contribute", ua: "вносити вклад", level: "B1" },
  { en: "deliver", ua: "доставляти", level: "B1" },
  { en: "expand", ua: "розширювати", level: "B1" },
  { en: "highlight", ua: "підкреслювати", level: "B1" },
  { en: "illustrate", ua: "ілюструвати", level: "B1" },
  { en: "motivate", ua: "мотивувати", level: "B1" },
  { en: "negotiate", ua: "вести переговори", level: "B1" },
  { en: "succeed", ua: "досягати успіху", level: "B1" },

  // Рівень B1
  { en: "accelerate", ua: "прискорювати", level: "B1" },
  { en: "accumulate", ua: "накопичувати", level: "B1" },
  { en: "advocate", ua: "захищати", level: "B1" },
  { en: "anticipate", ua: "очікувати", level: "B1" },
  { en: "assimilate", ua: "засвоювати", level: "B1" },
  { en: "authenticate", ua: "автентифікувати", level: "B1" },
  { en: "comprehend", ua: "зрозуміти", level: "B1" },
  { en: "coordinate", ua: "координувати", level: "B1" },
  // Рівень B1
  { en: "achieve", ua: "досягати", level: "B1" },
  { en: "clarify", ua: "уточнювати", level: "B1" },
  { en: "collaborate", ua: "співпрацювати", level: "B1" },
  { en: "construct", ua: "будувати", level: "B1" },
  { en: "demonstrate", ua: "демонструвати", level: "B1" },
  { en: "formulate", ua: "формулювати", level: "B1" },
  { en: "generate", ua: "створювати", level: "B1" },
  { en: "justify", ua: "обґрунтовувати", level: "B1" },
  { en: "monitor", ua: "відстежувати", level: "B1" },
  { en: "utilize", ua: "використовувати", level: "B1" },

  // Рівень B1
  { en: "allocate", ua: "розподіляти", level: "B1" },
  { en: "analyze", ua: "аналізувати", level: "B1" },
  { en: "articulate", ua: "чітко формулювати", level: "B1" },
  { en: "consolidate", ua: "зміцнювати", level: "B1" },
  { en: "cultivate", ua: "вирощувати", level: "B1" },
  { en: "debate", ua: "дискутувати", level: "B1" },
  { en: "elaborate", ua: "деталізувати", level: "B1" },
  { en: "facilitate", ua: "сприяти", level: "B1" },
  { en: "hypothesize", ua: "висувати гіпотези", level: "B1" },
  { en: "legitimize", ua: "легалізувати", level: "B1" },
  // Рівень B1 - Іменники (Nouns)
  { en: "achievement", ua: "досягнення", level: "B1" },
  { en: "advantage", ua: "перевага", level: "B1" },
  { en: "community", ua: "спільнота", level: "B1" },
  { en: "effort", ua: "зусилля", level: "B1" },
  { en: "goal", ua: "мета", level: "B1" },
  { en: "impact", ua: "вплив", level: "B1" },
  { en: "knowledge", ua: "знання", level: "B1" },
  { en: "progress", ua: "прогрес", level: "B1" },
  { en: "solution", ua: "рішення", level: "B1" },

  // Рівень B1 - Прикметники (Adjectives)
  { en: "accurate", ua: "точний", level: "B1" },
  { en: "ambitious", ua: "амбіційний", level: "B1" },
  { en: "complex", ua: "складний", level: "B1" },
  { en: "confident", ua: "впевнений", level: "B1" },
  { en: "effective", ua: "ефективний", level: "B1" },
  { en: "impressive", ua: "вражаючий", level: "B1" },
  { en: "logical", ua: "логічний", level: "B1" },
  { en: "practical", ua: "практичний", level: "B1" },
  { en: "reliable", ua: "надійний", level: "B1" },
  { en: "unique", ua: "унікальний", level: "B1" },

  // Рівень B1 - Дієслова (Verbs)
  { en: "collaborate", ua: "співпрацювати", level: "B1" },
  { en: "contribute", ua: "вносити вклад", level: "B1" },
  { en: "deliver", ua: "доставляти", level: "B1" },
  { en: "evaluate", ua: "оцінювати", level: "B1" },
  { en: "improve", ua: "покращувати", level: "B1" },
  { en: "influence", ua: "впливати", level: "B1" },
  { en: "motivate", ua: "мотивувати", level: "B1" },
  { en: "negotiate", ua: "вести переговори", level: "B1" },
  { en: "resolve", ua: "вирішувати", level: "B1" },

  // Рівень B1 - Іменники (Nouns)
  { en: "concept", ua: "концепція", level: "B1" },
  { en: "debate", ua: "дискусія", level: "B1" },
  { en: "emphasis", ua: "наголос", level: "B1" },
  { en: "innovation", ua: "інновація", level: "B1" },
  { en: "justification", ua: "обґрунтування", level: "B1" },
  { en: "perspective", ua: "перспектива", level: "B1" },
  { en: "priority", ua: "пріоритет", level: "B1" },
  { en: "trend", ua: "тенденція", level: "B1" },
  { en: "vision", ua: "бачення", level: "B1" },

  // Рівень B1 - Прикметники (Adjectives)
  { en: "advanced", ua: "просунутий", level: "B1" },
  { en: "appropriate", ua: "відповідний", level: "B1" },
  { en: "consistent", ua: "послідовний", level: "B1" },
  { en: "crucial", ua: "вирішальний", level: "B1" },
  { en: "innovative", ua: "інноваційний", level: "B1" },
  { en: "intellectual", ua: "інтелектуальний", level: "B1" },
  { en: "relevant", ua: "актуальний", level: "B1" },
  { en: "sustainable", ua: "стійкий", level: "B1" },

  // Рівень B1 - Дієслова (Verbs)
  { en: "anticipate", ua: "очікувати", level: "B1" },
  { en: "assess", ua: "оцінювати", level: "B1" },
  { en: "clarify", ua: "уточнювати", level: "B1" },
  { en: "coordinate", ua: "координувати", level: "B1" },
  { en: "differentiate", ua: "розрізняти", level: "B1" },
  { en: "elaborate", ua: "деталізувати", level: "B1" },
  { en: "facilitate", ua: "сприяти", level: "B1" },
  { en: "formulate", ua: "формулювати", level: "B1" },
  { en: "implement", ua: "впроваджувати", level: "B1" },
  { en: "synthesize", ua: "синтезувати", level: "B1" },
  // Рівень B1 - Іменники (Nouns)
  { en: "accuracy", ua: "точність", level: "B1" },
  { en: "analysis", ua: "аналіз", level: "B1" },
  { en: "approach", ua: "підхід", level: "B1" },
  { en: "argument", ua: "аргумент", level: "B1" },
  { en: "assumption", ua: "припущення", level: "B1" },
  { en: "circumstance", ua: "обставина", level: "B1" },
  { en: "consequence", ua: "наслідок", level: "B1" },
  { en: "hypothesis", ua: "гіпотеза", level: "B1" },
  { en: "interpretation", ua: "інтерпретація", level: "B1" },
  { en: "phenomenon", ua: "явище", level: "B1" },

  // Рівень B1 - Прикметники (Adjectives)
  { en: "advanced", ua: "просунутий", level: "B1" },
  { en: "beneficial", ua: "корисний", level: "B1" },
  { en: "challenging", ua: "складний", level: "B1" },
  { en: "comprehensive", ua: "всебічний", level: "B1" },
  { en: "essential", ua: "необхідний", level: "B1" },
  { en: "flexible", ua: "гнучкий", level: "B1" },
  { en: "innovative", ua: "інноваційний", level: "B1" },
  { en: "relevant", ua: "актуальний", level: "B1" },
  { en: "significant", ua: "значний", level: "B1" },
  { en: "sustainable", ua: "стійкий", level: "B1" },

  // Рівень B1 - Дієслова (Verbs)
  { en: "acknowledge", ua: "визнавати", level: "B1" },
  { en: "anticipate", ua: "очікувати", level: "B1" },
  { en: "conclude", ua: "робити висновок", level: "B1" },
  { en: "differentiate", ua: "розрізняти", level: "B1" },
  { en: "elaborate", ua: "деталізувати", level: "B1" },
  { en: "evaluate", ua: "оцінювати", level: "B1" },
  { en: "facilitate", ua: "сприяти", level: "B1" },
  { en: "implement", ua: "впроваджувати", level: "B1" },
  { en: "interpret", ua: "інтерпретувати", level: "B1" },
  { en: "synthesize", ua: "синтезувати", level: "B1" },
  // Рівень B1 - Іменники (Nouns)
  { en: "recommendation", ua: "рекомендація", level: "B1" },
  { en: "requirement", ua: "вимога", level: "B1" },
  { en: "resource", ua: "ресурс", level: "B1" },
  { en: "solution", ua: "рішення", level: "B1" },
  { en: "trend", ua: "тенденція", level: "B1" },
  { en: "evaluation", ua: "оцінка", level: "B1" },

  // Рівень B1 - Прикметники (Adjectives)
  { en: "appropriate", ua: "відповідний", level: "B1" },
  { en: "consistent", ua: "послідовний", level: "B1" },
  { en: "crucial", ua: "вирішальний", level: "B1" },
  { en: "dynamic", ua: "динамічний", level: "B1" },
  { en: "efficient", ua: "ефективний", level: "B1" },
  { en: "logical", ua: "логічний", level: "B1" },
  { en: "practical", ua: "практичний", level: "B1" },
  { en: "reliable", ua: "надійний", level: "B1" },
  { en: "unique", ua: "унікальний", level: "B1" },

  // Рівень B1 - Дієслова (Verbs)
  { en: "assess", ua: "оцінювати", level: "B1" },
  { en: "clarify", ua: "уточнювати", level: "B1" },
  { en: "coordinate", ua: "координувати", level: "B1" },
  { en: "debate", ua: "дискутувати", level: "B1" },
  { en: "demonstrate", ua: "демонструвати", level: "B1" },
  { en: "illustrate", ua: "ілюструвати", level: "B1" },
  { en: "investigate", ua: "розслідувати", level: "B1" },
  { en: "justify", ua: "обґрунтовувати", level: "B1" },
  { en: "optimize", ua: "оптимізувати", level: "B1" },
  { en: "prioritize", ua: "пріоритезувати", level: "B1" },
  // Рівень B1 - Іменники (Nouns)
  { en: "clarity", ua: "ясність", level: "B1" },
  { en: "complexity", ua: "складність", level: "B1" },
  { en: "consistency", ua: "послідовність", level: "B1" },
  { en: "innovation", ua: "інновація", level: "B1" },
  { en: "obligation", ua: "зобов'язання", level: "B1" },
  { en: "opportunity", ua: "можливість", level: "B1" },
  { en: "perception", ua: "сприйняття", level: "B1" },
  { en: "potential", ua: "потенціал", level: "B1" },
  { en: "recommendation", ua: "рекомендація", level: "B1" },
  { en: "requirement", ua: "вимога", level: "B1" },

  // Рівень B1 - Прикметники (Adjectives)
  { en: "accessible", ua: "доступний", level: "B1" },
  { en: "accurate", ua: "точний", level: "B1" },
  { en: "adequate", ua: "адекватний", level: "B1" },
  { en: "affordable", ua: "доступний за ціною", level: "B1" },
  { en: "beneficial", ua: "корисний", level: "B1" },
  { en: "comprehensive", ua: "всебічний", level: "B1" },
  { en: "consistent", ua: "послідовний", level: "B1" },
  { en: "dynamic", ua: "динамічний", level: "B1" },
  { en: "efficient", ua: "ефективний", level: "B1" },
  { en: "innovative", ua: "інноваційний", level: "B1" },

  // Рівень B1 - Дієслова (Verbs)
  { en: "anticipate", ua: "очікувати", level: "B1" },
  { en: "acknowledge", ua: "визнавати", level: "B1" },
  { en: "advocate", ua: "захищати", level: "B1" },
  { en: "assign", ua: "призначати", level: "B1" },
  { en: "clarify", ua: "уточнювати", level: "B1" },
  { en: "coordinate", ua: "координувати", level: "B1" },
  { en: "diversify", ua: "урізноманітнювати", level: "B1" },
  { en: "facilitate", ua: "сприяти", level: "B1" },
  { en: "implement", ua: "впроваджувати", level: "B1" },
  { en: "integrate", ua: "інтегрувати", level: "B1" },
  // Рівень B1 - Іменники (Nouns)
  { en: "evaluation", ua: "оцінка", level: "B1" },
  { en: "function", ua: "функція", level: "B1" },
  { en: "impact", ua: "вплив", level: "B1" },
  { en: "insight", ua: "розуміння", level: "B1" },
  { en: "integration", ua: "інтеграція", level: "B1" },
  { en: "priority", ua: "пріоритет", level: "B1" },
  { en: "reliability", ua: "надійність", level: "B1" },

  // Рівень B1 - Прикметники (Adjectives)
  { en: "logical", ua: "логічний", level: "B1" },
  { en: "objective", ua: "об'єктивний", level: "B1" },
  { en: "practical", ua: "практичний", level: "B1" },
  { en: "reliable", ua: "надійний", level: "B1" },
  { en: "rigorous", ua: "ретельний", level: "B1" },
  { en: "robust", ua: "міцний", level: "B1" },
  { en: "sustainable", ua: "стійкий", level: "B1" },
  { en: "transformative", ua: "трансформаційний", level: "B1" },
  { en: "unique", ua: "унікальний", level: "B1" },
  { en: "valuable", ua: "цінний", level: "B1" },

  // Рівень B1 - Дієслова (Verbs)
  { en: "sustain", ua: "підтримувати", level: "B1" },
  { en: "validate", ua: "підтверджувати", level: "B1" },
  { en: "utilize", ua: "використовувати", level: "B1" },

  { en: "optimize", ua: "оптимізувати", level: "B1" },
  { en: "prioritize", ua: "пріоритезувати", level: "B1" },
  { en: "conclude", ua: "робити висновок", level: "B1" },
  { en: "investigate", ua: "розслідувати", level: "B1" },
  { en: "synthesize", ua: "синтезувати", level: "B1" },
  // Рівень B1 - Іменники (Nouns)
  { en: "flexibility", ua: "гнучкість", level: "B1" },
  { en: "efficiency", ua: "ефективність", level: "B1" },
  { en: "sustainability", ua: "сталий розвиток", level: "B1" },
  { en: "credibility", ua: "достовірність", level: "B1" },
  { en: "innovation", ua: "інновація", level: "B1" },
  { en: "perception", ua: "сприйняття", level: "B1" },
  { en: "implementation", ua: "впровадження", level: "B1" },
  { en: "integration", ua: "інтеграція", level: "B1" },
  { en: "evaluation", ua: "оцінка", level: "B1" },
  { en: "adaptability", ua: "адаптивність", level: "B1" },

  // Рівень B1 - Прикметники (Adjectives)
  { en: "sustainable", ua: "стійкий", level: "B1" },
  { en: "credible", ua: "достовірний", level: "B1" },
  { en: "flexible", ua: "гнучкий", level: "B1" },
  { en: "efficient", ua: "ефективний", level: "B1" },
  { en: "dynamic", ua: "динамічний", level: "B1" },
  { en: "innovative", ua: "інноваційний", level: "B1" },
  { en: "practical", ua: "практичний", level: "B1" },
  { en: "reliable", ua: "надійний", level: "B1" },
  { en: "adaptable", ua: "адаптивний", level: "B1" },
  { en: "accurate", ua: "точний", level: "B1" },

  // Рівень B1 - Дієслова (Verbs)
  { en: "evaluate", ua: "оцінювати", level: "B1" },
  { en: "implement", ua: "впроваджувати", level: "B1" },
  { en: "integrate", ua: "інтегрувати", level: "B1" },
  { en: "synthesize", ua: "синтезувати", level: "B1" },
  { en: "prioritize", ua: "пріоритезувати", level: "B1" },
  { en: "facilitate", ua: "сприяти", level: "B1" },
  { en: "adapt", ua: "адаптуватися", level: "B1" },

  // Рівень B1 - Іменники (Nouns)
  { en: "transformation", ua: "трансформація", level: "B1" },
  { en: "adaptation", ua: "адаптація", level: "B1" },
  { en: "assessment", ua: "оцінювання", level: "B1" },
  { en: "collaboration", ua: "співпраця", level: "B1" },
  { en: "integration", ua: "інтеграція", level: "B1" },
  { en: "initiative", ua: "ініціатива", level: "B1" },
  { en: "flexibility", ua: "гнучкість", level: "B1" },
  { en: "innovation", ua: "інновація", level: "B1" },
  { en: "implementation", ua: "впровадження", level: "B1" },

  // Рівень B1 - Прикметники (Adjectives)
  { en: "effective", ua: "ефективний", level: "B1" },
  { en: "innovative", ua: "інноваційний", level: "B1" },
  { en: "dynamic", ua: "динамічний", level: "B1" },
  { en: "adaptable", ua: "адаптивний", level: "B1" },
  { en: "comprehensive", ua: "всебічний", level: "B1" },
  { en: "reliable", ua: "надійний", level: "B1" },
  { en: "accurate", ua: "точний", level: "B1" },
  { en: "flexible", ua: "гнучкий", level: "B1" },
  { en: "practical", ua: "практичний", level: "B1" },
  { en: "sustainable", ua: "стійкий", level: "B1" },

  // Рівень B1 - Дієслова (Verbs)
  { en: "adapt", ua: "адаптуватися", level: "B1" },
  { en: "assess", ua: "оцінювати", level: "B1" },
  { en: "facilitate", ua: "сприяти", level: "B1" },
  { en: "implement", ua: "впроваджувати", level: "B1" },
  { en: "integrate", ua: "інтегрувати", level: "B1" },
  { en: "optimize", ua: "оптимізувати", level: "B1" },
  { en: "prioritize", ua: "пріоритезувати", level: "B1" },
  { en: "synthesize", ua: "синтезувати", level: "B1" },
  { en: "transform", ua: "трансформувати", level: "B1" },
  { en: "evaluate", ua: "оцінювати", level: "B1" },
  // Рівень B1 - Іменники (Nouns)
  { en: "accuracy", ua: "точність", level: "B1" },
  { en: "adaptation", ua: "адаптація", level: "B1" },
  { en: "assessment", ua: "оцінювання", level: "B1" },
  { en: "credibility", ua: "достовірність", level: "B1" },
  { en: "efficiency", ua: "ефективність", level: "B1" },
  { en: "flexibility", ua: "гнучкість", level: "B1" },
  { en: "implementation", ua: "впровадження", level: "B1" },
  { en: "integration", ua: "інтеграція", level: "B1" },
  { en: "opportunity", ua: "можливість", level: "B1" },
  { en: "priority", ua: "пріоритет", level: "B1" },

  // Рівень B1 - Прикметники (Adjectives)
  { en: "accessible", ua: "доступний", level: "B1" },
  { en: "adequate", ua: "адекватний", level: "B1" },
  { en: "comprehensive", ua: "всебічний", level: "B1" },
  { en: "dynamic", ua: "динамічний", level: "B1" },
  { en: "efficient", ua: "ефективний", level: "B1" },
  { en: "innovative", ua: "інноваційний", level: "B1" },
  { en: "reliable", ua: "надійний", level: "B1" },
  { en: "sustainable", ua: "стійкий", level: "B1" },
  { en: "valuable", ua: "цінний", level: "B1" },
  { en: "adaptable", ua: "адаптивний", level: "B1" },

  // Рівень B1 - Дієслова (Verbs)
  { en: "anticipate", ua: "очікувати", level: "B1" },
  { en: "assess", ua: "оцінювати", level: "B1" },
  { en: "clarify", ua: "уточнювати", level: "B1" },
  { en: "coordinate", ua: "координувати", level: "B1" },
  { en: "facilitate", ua: "сприяти", level: "B1" },
  { en: "implement", ua: "впроваджувати", level: "B1" },
  { en: "integrate", ua: "інтегрувати", level: "B1" },
  { en: "optimize", ua: "оптимізувати", level: "B1" },
  { en: "prioritize", ua: "пріоритезувати", level: "B1" },
  { en: "synthesize", ua: "синтезувати", level: "B1" },
  // Рівень B1 - Іменники (Nouns)
  { en: "strategy", ua: "стратегія", level: "B1" },
  { en: "evaluation", ua: "оцінка", level: "B1" },
  { en: "initiative", ua: "ініціатива", level: "B1" },
  { en: "collaboration", ua: "співпраця", level: "B1" },
  { en: "adaptability", ua: "адаптивність", level: "B1" },
  { en: "insight", ua: "розуміння", level: "B1" },
  { en: "transformation", ua: "трансформація", level: "B1" },
  { en: "function", ua: "функція", level: "B1" },
  { en: "credibility", ua: "достовірність", level: "B1" },
  { en: "trend", ua: "тенденція", level: "B1" },

  // Рівень B1 - Прикметники (Adjectives)
  { en: "objective", ua: "об'єктивний", level: "B1" },
  { en: "logical", ua: "логічний", level: "B1" },
  { en: "effective", ua: "ефективний", level: "B1" },
  { en: "unique", ua: "унікальний", level: "B1" },
  { en: "robust", ua: "міцний", level: "B1" },
  { en: "accurate", ua: "точний", level: "B1" },
  { en: "transformative", ua: "трансформаційний", level: "B1" },
  { en: "reliable", ua: "надійний", level: "B1" },
  { en: "valuable", ua: "цінний", level: "B1" },
  { en: "practical", ua: "практичний", level: "B1" },

  // Рівень B1 - Дієслова (Verbs)
  { en: "transform", ua: "трансформувати", level: "B1" },
  { en: "evaluate", ua: "оцінювати", level: "B1" },
  { en: "integrate", ua: "інтегрувати", level: "B1" },
  { en: "sustain", ua: "підтримувати", level: "B1" },
  { en: "validate", ua: "підтверджувати", level: "B1" },
  { en: "utilize", ua: "використовувати", level: "B1" },
  { en: "adapt", ua: "адаптуватися", level: "B1" },
  { en: "optimize", ua: "оптимізувати", level: "B1" },
  { en: "prioritize", ua: "пріоритезувати", level: "B1" },
  { en: "conclude", ua: "робити висновок", level: "B1" },

  // Рівень B1
  { en: "responsibility", ua: "відповідальність", level: "B1" },
  { en: "confidence", ua: "впевненість", level: "B1" },
  { en: "decision", ua: "рішення", level: "B1" },
  { en: "consideration", ua: "розгляд", level: "B1" },
  // Рівень B1 - Іменники (Nouns)
  { en: "adjustment", ua: "коригування", level: "B1" },
  { en: "allocation", ua: "розподіл", level: "B1" },
  { en: "assumption", ua: "припущення", level: "B1" },
  { en: "breakthrough", ua: "прорив", level: "B1" },
  { en: "collaboration", ua: "співпраця", level: "B1" },
  { en: "constraint", ua: "обмеження", level: "B1" },
  { en: "contribution", ua: "внесок", level: "B1" },
  { en: "dedication", ua: "присвячення", level: "B1" },
  { en: "expansion", ua: "розширення", level: "B1" },
  { en: "precision", ua: "точність", level: "B1" },

  // Рівень B1 - Прикметники (Adjectives)
  { en: "ambiguous", ua: "двозначний", level: "B1" },
  { en: "coherent", ua: "зв'язний", level: "B1" },
  { en: "consecutive", ua: "послідовний", level: "B1" },
  { en: "contingent", ua: "залежний від обставин", level: "B1" },
  { en: "diverse", ua: "різноманітний", level: "B1" },
  { en: "explicit", ua: "чіткий", level: "B1" },
  { en: "feasible", ua: "здійсненний", level: "B1" },
  { en: "indispensable", ua: "незамінний", level: "B1" },
  { en: "plausible", ua: "правдоподібний", level: "B1" },
  { en: "substantial", ua: "істотний", level: "B1" },

  // Рівень B1 - Дієслова (Verbs)
  { en: "accommodate", ua: "пристосовувати", level: "B1" },
  { en: "ascertain", ua: "з'ясовувати", level: "B1" },
  { en: "compile", ua: "компілювати", level: "B1" },
  { en: "delegate", ua: "делегувати", level: "B1" },
  { en: "derive", ua: "отримувати", level: "B1" },
  { en: "enhance", ua: "покращувати", level: "B1" },
  { en: "incorporate", ua: "включати", level: "B1" },
  { en: "manipulate", ua: "маніпулювати", level: "B1" },
  { en: "regulate", ua: "регулювати", level: "B1" },
  { en: "streamline", ua: "оптимізувати", level: "B1" },
  // Рівень B1 - Іменники (Nouns)
  { en: "modification", ua: "зміна", level: "B1" },
  { en: "overview", ua: "огляд", level: "B1" },
  { en: "perception", ua: "сприйняття", level: "B1" },
  { en: "prioritization", ua: "визначення пріоритетів", level: "B1" },
  { en: "resolution", ua: "рішення", level: "B1" },
  { en: "specification", ua: "специфікація", level: "B1" },
  { en: "sustainability", ua: "сталий розвиток", level: "B1" },
  { en: "validation", ua: "підтвердження", level: "B1" },
  { en: "variability", ua: "мінливість", level: "B1" },
  { en: "viability", ua: "життєздатність", level: "B1" },

  // Рівень B1 - Прикметники (Adjectives)
  { en: "accessible", ua: "доступний", level: "B1" },
  { en: "adaptable", ua: "адаптивний", level: "B1" },
  { en: "analytical", ua: "аналітичний", level: "B1" },
  { en: "complementary", ua: "доповнювальний", level: "B1" },
  { en: "comprehensive", ua: "всебічний", level: "B1" },
  { en: "deliberate", ua: "навмисний", level: "B1" },
  { en: "dynamic", ua: "динамічний", level: "B1" },
  { en: "feasible", ua: "здійсненний", level: "B1" },
  { en: "holistic", ua: "цілісний", level: "B1" },
  { en: "innovative", ua: "інноваційний", level: "B1" },

  // Рівень B1 - Дієслова (Verbs)
  { en: "articulate", ua: "чітко формулювати", level: "B1" },
  { en: "bolster", ua: "підтримувати", level: "B1" },
  { en: "deviate", ua: "відхилятися", level: "B1" },
  { en: "emphasize", ua: "наголошувати", level: "B1" },
  { en: "exemplify", ua: "слугувати прикладом", level: "B1" },
  { en: "expedite", ua: "прискорювати", level: "B1" },
  { en: "illustrate", ua: "ілюструвати", level: "B1" },
  { en: "influence", ua: "впливати", level: "B1" },
  { en: "maximize", ua: "максимізувати", level: "B1" },
  { en: "rationalize", ua: "раціоналізувати", level: "B1" },
  // Рівень B1 - Іменники (Nouns)
  { en: "acquisition", ua: "придбання", level: "B1" },
  { en: "affiliation", ua: "афіліація", level: "B1" },
  { en: "alignment", ua: "вирівнювання", level: "B1" },
  { en: "attainment", ua: "досягнення", level: "B1" },
  { en: "competence", ua: "компетентність", level: "B1" },
  { en: "discretion", ua: "розсуд", level: "B1" },
  { en: "initiative", ua: "ініціатива", level: "B1" },
  { en: "justification", ua: "обґрунтування", level: "B1" },
  { en: "proficiency", ua: "майстерність", level: "B1" },
  { en: "viability", ua: "життєздатність", level: "B1" },

  // Рівень B1 - Прикметники (Adjectives)
  { en: "accountable", ua: "відповідальний", level: "B1" },
  { en: "artificial", ua: "штучний", level: "B1" },
  { en: "compulsory", ua: "обов'язковий", level: "B1" },
  { en: "contingent", ua: "залежний", level: "B1" },
  { en: "indispensable", ua: "незамінний", level: "B1" },
  { en: "integral", ua: "невід'ємний", level: "B1" },
  { en: "notable", ua: "значущий", level: "B1" },
  { en: "plausible", ua: "правдоподібний", level: "B1" },
  { en: "prevalent", ua: "поширений", level: "B1" },
  { en: "redundant", ua: "надлишковий", level: "B1" },

  // Рівень B1 - Дієслова (Verbs)
  { en: "allocate", ua: "розподіляти", level: "B1" },
  { en: "apprehend", ua: "затримувати", level: "B1" },
  { en: "attain", ua: "досягати", level: "B1" },
  { en: "bolster", ua: "підтримувати", level: "B1" },
  { en: "consolidate", ua: "зміцнювати", level: "B1" },
  { en: "counteract", ua: "протидіяти", level: "B1" },
  { en: "deem", ua: "вважати", level: "B1" },
  { en: "expedite", ua: "прискорювати", level: "B1" },
  { en: "maintain", ua: "підтримувати", level: "B1" },
  { en: "underscore", ua: "підкреслювати", level: "B1" },
  // Рівень B1 - Іменники (Nouns)
  { en: "allocation", ua: "розподіл", level: "B1" },
  { en: "ambiguity", ua: "двозначність", level: "B1" },
  { en: "dedication", ua: "відданість", level: "B1" },
  { en: "derivation", ua: "похідність", level: "B1" },
  { en: "discipline", ua: "дисципліна", level: "B1" },
  { en: "elaboration", ua: "розробка", level: "B1" },
  { en: "execution", ua: "виконання", level: "B1" },
  { en: "implication", ua: "наслідок", level: "B1" },
  { en: "likelihood", ua: "ймовірність", level: "B1" },
  { en: "sophistication", ua: "витонченість", level: "B1" },

  // Рівень B1 - Прикметники (Adjectives)
  { en: "coherent", ua: "зв'язний", level: "B1" },
  { en: "cumulative", ua: "накопичувальний", level: "B1" },
  { en: "deterrent", ua: "стримувальний", level: "B1" },
  { en: "diminished", ua: "зменшений", level: "B1" },
  { en: "hierarchical", ua: "ієрархічний", level: "B1" },
  { en: "intrinsic", ua: "властивий", level: "B1" },
  { en: "marginal", ua: "незначний", level: "B1" },
  { en: "multifaceted", ua: "багатогранний", level: "B1" },
  { en: "rigorous", ua: "ретельний", level: "B1" },
  { en: "underlying", ua: "основний", level: "B1" },

  // Рівень B1 - Дієслова (Verbs)
  { en: "amplify", ua: "посилювати", level: "B1" },
  { en: "ascertain", ua: "виявляти", level: "B1" },
  { en: "complement", ua: "доповнювати", level: "B1" },
  { en: "corroborate", ua: "підтверджувати", level: "B1" },
  { en: "deplete", ua: "вичерпувати", level: "B1" },
  { en: "diverge", ua: "розходитися", level: "B1" },
  { en: "exacerbate", ua: "загострювати", level: "B1" },
  { en: "facilitate", ua: "сприяти", level: "B1" },
  { en: "moderate", ua: "пом'якшувати", level: "B1" },
  { en: "substantiate", ua: "обґрунтовувати", level: "B1" },

  // Рівень C1
  { en: "scrutinize", ua: "ретельно вивчати", level: "C1" },
  { en: "commence", ua: "розпочинати", level: "C1" },
  { en: "elucidate", ua: "пояснити", level: "C1" },
  { en: "comprehensive", ua: "всебічний", level: "C1" },

  { en: "abstraction", ua: "абстракція", level: "C1" },
{ en: "adversity", ua: "невзгоди", level: "C1" },
{ en: "allegation", ua: "заява", level: "C1" },
{ en: "aspiration", ua: "стремління", level: "C1" },
{ en: "coincidence", ua: "збіг", level: "C1" },
{ en: "contingency", ua: "непередбачувана ситуація", level: "C1" },
{ en: "disposition", ua: "характер", level: "C1" },
{ en: "elucidation", ua: "пояснення", level: "C1" },
{ en: "inference", ua: "висновок", level: "C1" },
{ en: "reconciliation", ua: "примирення", level: "C1" },

// Рівень C1 - Прикметники (Adjectives)
{ en: "astute", ua: "проникливий", level: "C1" },
{ en: "candid", ua: "відвертий", level: "C1" },
{ en: "cohesive", ua: "згуртований", level: "C1" },
{ en: "compelling", ua: "переконливий", level: "C1" },
{ en: "cumbersome", ua: "незграбний", level: "C1" },
{ en: "devious", ua: "хитромудрий", level: "C1" },
{ en: "exorbitant", ua: "надмірний", level: "C1" },
{ en: "implicit", ua: "неявний", level: "C1" },
{ en: "inquisitive", ua: "допитливий", level: "C1" },
{ en: "tedious", ua: "нудний", level: "C1" },

// Рівень C1 - Дієслова (Verbs)
{ en: "advocate", ua: "відстоювати", level: "C1" },
{ en: "alleviate", ua: "полегшувати", level: "C1" },
{ en: "circumvent", ua: "обходити", level: "C1" },
{ en: "contradict", ua: "заперечувати", level: "C1" },
{ en: "deviate", ua: "відхилятися", level: "C1" },
{ en: "discern", ua: "розпізнавати", level: "C1" },
{ en: "eradicate", ua: "викорінювати", level: "C1" },
{ en: "exacerbate", ua: "загострювати", level: "C1" },
{ en: "fluctuate", ua: "коливатися", level: "C1" },
{ en: "scrutinize", ua: "ретельно перевіряти", level: "C1" },

// Рівень C1 - Іменники (Nouns)
{ en: "abstraction", ua: "абстракція", level: "C1" },
{ en: "adversity", ua: "невзгоди", level: "C1" },
{ en: "allegation", ua: "заява", level: "C1" },
{ en: "aspiration", ua: "стремління", level: "C1" },
{ en: "coincidence", ua: "збіг", level: "C1" },
{ en: "contingency", ua: "непередбачувана ситуація", level: "C1" },
{ en: "disposition", ua: "характер", level: "C1" },
{ en: "elucidation", ua: "пояснення", level: "C1" },
{ en: "inference", ua: "висновок", level: "C1" },
{ en: "reconciliation", ua: "примирення", level: "C1" },

// Рівень C1 - Прикметники (Adjectives)
{ en: "astute", ua: "проникливий", level: "C1" },
{ en: "candid", ua: "відвертий", level: "C1" },
{ en: "cohesive", ua: "згуртований", level: "C1" },
{ en: "compelling", ua: "переконливий", level: "C1" },
{ en: "cumbersome", ua: "незграбний", level: "C1" },
{ en: "devious", ua: "хитромудрий", level: "C1" },
{ en: "exorbitant", ua: "надмірний", level: "C1" },
{ en: "implicit", ua: "неявний", level: "C1" },
{ en: "inquisitive", ua: "допитливий", level: "C1" },
{ en: "tedious", ua: "нудний", level: "C1" },

// Рівень C1 - Дієслова (Verbs)
{ en: "advocate", ua: "відстоювати", level: "C1" },
{ en: "alleviate", ua: "полегшувати", level: "C1" },
{ en: "circumvent", ua: "обходити", level: "C1" },
{ en: "contradict", ua: "заперечувати", level: "C1" },
{ en: "deviate", ua: "відхилятися", level: "C1" },
{ en: "discern", ua: "розпізнавати", level: "C1" },
{ en: "eradicate", ua: "викорінювати", level: "C1" },
{ en: "exacerbate", ua: "загострювати", level: "C1" },
{ en: "fluctuate", ua: "коливатися", level: "C1" },
{ en: "scrutinize", ua: "ретельно перевіряти", level: "C1" },
];

// function countByLevel(wordPairs) {
//   return wordPairs.reduce((acc, word) => {
//     acc[word.level] = (acc[word.level] || 0) + 1;
//     return acc;
//   }, {});
// }

// console.log(countByLevel(wordPairs));
// порахувать скіки слів уже

function getUniqueWords(uniquePairs) {
  const seen = new Set();

  for (const word of uniquePairs) {
    if (!seen.has(word.en)) {
      seen.add(word.en);
      wordPairs.push(word);
    }
  }

  return wordPairs;
}
getUniqueWords(uniquePairs);

function countWordsByLevel(wordPairs) {
  const counts = {};

  for (const word of wordPairs) {
    const level = word.level;

    if (counts[level]) {
      counts[level]++;
    } else {
      counts[level] = 1;
    }
  }

  return counts;
}
const levelCounts = countWordsByLevel(wordPairs);
console.log("📊 Кількість слів по рівнях:", levelCounts);

export { wordPairs };
